# Generated by Django 6.0.4 on 2026-08-12 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'verbose_name': 'Staff profile', 'verbose_name_plural': 'Staff profiles'},
        ),
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'verbose_name': 'Teacher profile', 'verbose_name_plural': 'Teacher profiles'},
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organization.organization'),
        ),
    ]
