# Generated by Django 6.0.4 on 2026-05-15 15:32

import apps.common.models.base
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(db_default=apps.common.models.base.GenRandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='organization.organization')),
            ],
            options={
                'unique_together': {('name', 'organization'), ('slug', 'organization')},
            },
        ),
    ]
