# Generated by Django 6.0.4 on 2026-05-15 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='enrollment.enrollment'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('enrollment', 'date'), name='unique_attendance'),
        ),
    ]
