# Generated by Django 6.0.4 on 2026-05-15 15:32

import apps.common.models.base
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.UUIDField(db_default=apps.common.models.base.GenRandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('action', models.CharField(choices=[('STUDENT_JOINED', 'Student joined group'), ('STUDENT_LEFT', 'Student left group'), ('GROUP_CREATED', 'Group created'), ('PAYMENT_DONE', 'Payment done'), ('TEACHER_CHANGED', 'Teacher changed')], max_length=255)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_history', to='course.group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
