# Generated by Django 6.0.4 on 2026-08-12 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_phase2_business_logic'),
        ('history', '0002_initial'),
        ('organization', '0001_initial'),
        ('users', '0002_phase1_model_fixes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-created_at'], 'verbose_name': 'History entry', 'verbose_name_plural': 'History entries'},
        ),
        migrations.AddField(
            model_name='history',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='Structured extra context for this action (e.g. transfer details).', verbose_name='Meta'),
        ),
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.CharField(choices=[('STUDENT_JOINED', 'Student joined group'), ('STUDENT_LEFT', 'Student left group'), ('STUDENT_TRANSFERRED', 'Student transferred to another group'), ('STUDENT_GRADUATED', 'Student graduated'), ('STUDENT_DROPPED', 'Student dropped out'), ('STUDENT_FROZEN', 'Student account frozen'), ('STUDENT_UNFROZEN', 'Student account unfrozen'), ('GROUP_CREATED', 'Group created'), ('TEACHER_CHANGED', 'Teacher changed on group'), ('LESSON_COMPLETED', 'Lesson marked as completed'), ('LESSON_CANCELLED', 'Lesson cancelled'), ('PAYMENT_DONE', 'Payment recorded')], db_index=True, max_length=255, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='history',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='history',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_history', to='course.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='history',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_performed', to=settings.AUTH_USER_MODEL, verbose_name='Performed by'),
        ),
        migrations.AlterField(
            model_name='history',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_history', to='users.studentprofile', verbose_name='Student'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['student', '-created_at'], name='history_student_created_idx'),
        ),
    ]
