# Generated by Django 6.0.4 on 2026-08-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_group_name'),
        ('organization', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='group',
            name='start_date',
            field=models.DateField(verbose_name='Group start date'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_group_name_per_org'),
        ),
    ]
