# Generated by Django 6.0.4 on 2026-08-12 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_phase1_model_fixes'),
        ('users', '0002_phase1_model_fixes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['date'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Who taught this lesson. Defaults to the group teacher.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='users.teacherprofile', verbose_name='Teacher'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='reason',
            field=models.CharField(blank=True, help_text='Required when status is CANCELLED.', max_length=500, null=True, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20, verbose_name='Status'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('group', 'date'), name='unique_lesson_per_group_per_date'),
        ),
    ]
