# Generated by Django 6.0.4 on 2026-05-15 15:32

import apps.common.models.base
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(db_default=apps.common.models.base.GenRandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umumiy summa')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='To‘langan summa')),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partial', 'Partial'), ('overdue', 'Overdue')], default='unpaid', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Naqd'), ('card', 'Plastik karta'), ('transfer', 'Bank o‘tkazmasi')], max_length=20, null=True)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='To‘lov muddati')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='To‘langan vaqti')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='course.course')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='course.group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
