# Generated by Django 6.0.4 on 2026-08-12 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_initial'),
        ('organization', '0001_initial'),
        ('payment', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateField(blank=True, help_text='The deadline by which this payment is expected.', null=True, verbose_name='Due date'),
        ),
        migrations.AddField(
            model_name='payment',
            name='enrollment',
            field=models.ForeignKey(blank=True, help_text='The specific group/course enrollment this payment is for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='enrollment.enrollment', verbose_name='Enrollment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='for_month',
            field=models.DateField(blank=True, help_text='The first day of the month this payment covers (e.g. 2026-09-01).', null=True, verbose_name='For month'),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who recorded this payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL, verbose_name='Received by'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(help_text='The actual date of payment. Can be manually set to a past date.', verbose_name='Payment date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('click', 'Click/Payme')], max_length=20, verbose_name='Payment type'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.studentprofile', verbose_name='Student'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student'], name='payment_student_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['due_date'], name='payment_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['for_month'], name='payment_for_month_idx'),
        ),
    ]
